version: "3"
services:
  app:
    build: .
    volumes:
      - .:/app
      - bundle-data:/usr/local/bundle/
    command: bash -c 'bundle install && bundle exec thor posts:archive'

volumes:
  bundle-data:
    driver: local
