version: 2.1
executors:
  default:
    parameters:
      tag:
        type: string

    docker:
      - image: circleci/ruby:<< parameters.tag >>
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle

    working_directory: ~/app

jobs:
  test:
    parameters:
      ruby-version:
        type: string

    executor:
      name: default
      tag: << parameters.ruby-version >>

    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-

      - checkout

      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - .git

      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-
      - run:
          name: Bundle Install
          command: bundle check || bundle install --path vendor/bundle

      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Rubocop
          command: bundle exec rubocop

      - run:
          name: Rspec
          command: bundle exec rspec

workflows:
  version: 2.1
  test:
    jobs:
      - test:
          name: "test-ruby24"
          ruby-version: "2.4.6"

      - test:
          name: "test-ruby25"
          ruby-version: "2.5.5"

      - test:
          name: "test-ruby26"
          ruby-version: "2.6.3"
