version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0

    steps:
      - checkout

      - restore_cache:
          keys:
            - esa-archiver-{{ checksum "Gemfile.lock" }}
            - esa-archiver-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - save_cache:
          key: esa-archiver-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Rubocop
          command: bundle exec rubocop

      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rspec --profile 10 \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      - store_test_results:
          path: test_results
